export const elements = {
  a: 'a',
  h1: 'h1',
  h2: 'h2',
  h4: 'h4',
  tr: 'tr',
  td: 'td',
  tbody: 'tbody',
  input: 'input',
  button: 'button',
  class: 'class',
  option: 'option',
  checkbox: 'input[class="pf-c-check__input"]',
  dialog: 'div[role="dialog"]',
  delete: '#delete',
  actionsButton: '#toggle-id',
  checkAll: '[name="check-all"]',
  selectMenuItem: '.pf-c-select__menu-item',
  pageMenu: '.pf-c-page__main > :nth-child(2)',
  deleteTableRowButtonClass: 'button[class="pf-c-dropdown__toggle pf-m-plain"]',
  pageClassKey: '.pf-c-page',
  pageNavLink: '.pf-c-nav__link',
  mainSection: '.pf-c-page__main-section',
  dialogPageCover: '.pf-l-bullseye',
  buttonClassKey: '.pf-c-empty-state__primary > .pf-c-button',
  disabledButton: 'pf-m-aria-disabled',
  pageSearch: 'input[aria-label="Search input"]',
  resetSearch: 'button[aria-label="Reset"]',
  dropDownToggleButton: 'button[aria-label="Options menu"]',
  dropDownMenu: '.pf-c-dropdown__menu',
  dropDownMenuItem: 'button.pf-c-dropdown__menu-item',
  xButton: 'button[aria-label="Close"]',
  lable: 'div[class="pf-c-form__group-label"]',
  currentTabClass: 'a[class="pf-c-nav__link pf-m-current"]',
  tabClass: 'a[class="pf-c-nav__link"]',
  radioInput: 'div[class="pf-c-radio"]',
  chipText: '.pf-c-chip__text',
  emptyContent: '.pf-c-empty-state__content',
  emptyBody: '.pf-c-empty-state__body',
  toolbarContentSection: '.pf-c-toolbar__content-section',
  title: '.pf-c-title',
  table: 'table',
  firstRowIndex: '1',
  submit: 'button[type="submit"]',
}

export const elementsText = {
  next: 'Next',
  add: 'Add',
  actions: 'Actions',
  approve: 'Approve',
  approveAll: 'Approve all hosts',
  create: 'Create',
  cancel: 'Cancel',
  close: 'Close',
  import: 'Import',
  save: 'Save',
  InstallCluster: 'Install cluster',
  delete: 'Delete',
  review: 'Review',
  remove: 'Remove',
  noResult: 'No results found',
  forbindden: 'Forbidden',
  forbiddenMsg:
    'You are not authorized to complete this action. See your cluster administrator for role-based access control information.',
}

export const alerts = {
  dangerAlert: '[aria-label="Danger Alert"]',
  alertTitle: '.pf-c-alert__title',
  alertIcon: '.pf-c-alert__icon',
  alertAction: '.pf-c-alert__action',
  alertDescrition: '.pf-c-alert__description',
}
